### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by lrkwz** [jonasrutishauser/wagon-git#2]
Just curiosity: any special reason you didn't you use http://synergian.github.io/wagon-git/ ?

**Comment by jonasrutishauser** [comment]
First of all it is not in maven central.

Secondly it misses many features i need.
The site plugin uses the hostname of the distribution management URL to determine if an absolute or relative link should be made.
My extension allows to set an arbitrary string as the "hostname" (it is simply ignored by my extension) such that the child projects don't use a relative URL.
Furthermore i wanted to be able to specify a directory in the git repository.
My distribution management URLs have to following form: `git://${root.artifactId}/https://github.com/jonasrutishauser/${root.artifactId}.git!gh-pages!${site.path}`

**Comment by lrkwz** [comment]
I find it quite difficult to configure on private repo (gitlab) can you suggest url?
Do you have docs anyware?

thnks

**Comment by jonasrutishauser** [comment]
There is no documentation so far.

The URL should have to following form (see [Parsing Pattern](../blob/ecac87734e1859bf5fa60116255272996692e55e/src/main/java/com/github/jonasrutishauser/maven/wagon/git/GitConfiguration.java#L34)):
```
git:(//<any-identifier>/)?<git-url>((!<branch-name>)?!<path-in-repo>)?
```

**Comment by lrkwz** [comment]
It would be really useful having a template: [gitlab api](https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository) lets you access (GET) files in this way:

    curl -H 'PRIVATE-TOKEN: xyz' https://gitlab.com/api/v4/projects/PROJECTID/repository/files/URLENCODED_FILE_PATH/raw\?ref\=releases

or

    curl -H 'PRIVATE-TOKEN: xyz' https://gitlab.com/api/v4/projects/PROJECTID/repository/files/URLENCODED_FILE_PATH/raw\?ref\=snapshots

Which could be described with something like:

```xml
    <repositories>
        <repository>
            <id>my-repo</id>
	    <url>https://gitlab.com/api/v4/projects/1234567890/repository/files/${urlencode path}/raw?ref=releases</url>
	    <snapshots><enabled>false</enabled></snapshots>
        </repository>
        <repository>
            <id>my-snapshots-repo</id>
	    <url>https://gitlab.com/api/v4/projects/1234567890/repository/files/${urlencode path}/raw?ref=snapshots</url>
	    <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>
```
